---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-processing-backend-uploads-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/image-processing-backend-uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-processing-backend-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-processing-backend-output-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/image-processing-backend-output
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-processing-backend-output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-backend
spec:
  selector:
    matchLabels:
      app: image-processing-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: image-processing-backend
    spec:
      containers:
      - name: backend
        image: navalbisht444/image-processing-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "image-processing-mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: image-processing-mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: image-processing-mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          value: "image_processing"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1024Mi"
        volumeMounts:
        - name: uploads
          mountPath: /app/Uploads
        - name: output
          mountPath: /app/output
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: image-processing-backend-uploads-pvc
      - name: output
        persistentVolumeClaim:
          claimName: image-processing-backend-output-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-processing-backend
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001
  selector:
    app: image-processing-backend
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: image-processing-backend-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: image-processing-backend
#   minReplicas: 1
#   maxReplicas: 3
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 70