---
# Elasticsearch PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-processing-elasticsearch-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/image-processing-elasticsearch
---
# Elasticsearch PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-processing-elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Elasticsearch Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-elasticsearch
spec:
  selector:
    matchLabels:
      app: image-processing-elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: image-processing-elasticsearch
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: image-processing-elasticsearch-pvc
---
# Elasticsearch Service
apiVersion: v1
kind: Service
metadata:
  name: image-processing-elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: image-processing-elasticsearch
---
# Elasticsearch HPA
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: image-processing-elasticsearch-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: image-processing-elasticsearch
#   minReplicas: 1
#   maxReplicas: 2
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50