---
# Filebeat ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-processing-filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    output.logstash:
      hosts: ["image-processing-logstash:5044"]
---
# Filebeat DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-processing-filebeat
spec:
  selector:
    matchLabels:
      app: image-processing-filebeat
  template:
    metadata:
      labels:
        app: image-processing-filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.8.0
          args: ["-c", "/etc/filebeat.yml", "-e"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          # resources:
          #   requests:
          #     cpu: "50m"
          #     memory: "100Mi"
          #   limits:
          #     cpu: "100m"
          #     memory: "200Mi"
      volumes:
        - name: config
          configMap:
            name: image-processing-filebeat-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers