---
# Kibana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processing-kibana
spec:
  selector:
    matchLabels:
      app: image-processing-kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: image-processing-kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.8.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://image-processing-elasticsearch:9200"
          # resources:
          #   requests:
          #     cpu: "100m"
          #     memory: "512Mi"
          #   limits:
          #     cpu: "200m"
          #     memory: "1Gi"
---
# Kibana Service
apiVersion: v1
kind: Service
metadata:
  name: image-processing-kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30007
  selector:
    app: image-processing-kibana
---
# Kibana HPA
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: image-processing-kibana-hpa
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: image-processing-kibana
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 50